name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install cmake qt6-base-dev libgl1-mesa-dev qt6-tools-dev qt6-l10n-tools qt6-tools-dev-tools qt6-multimedia-dev

    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Make
      run: cmake --build build -j $(nproc)

    - name: Upload
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: D1HeroPlanner-Linux-x64
        path: build/D1HeroPlanner
