name: Windows-x86

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'win32_msvc2019'
        cache: 'true'

    - name: Configure
      run: cmake -S. -Bbuild -A Win32

    - name: Make
      run: cmake --build build -j $(nproc)

    - name: Package
      run: |
        mkdir dist
        copy build\Debug\D1HeroPlanner.exe dist
        cd dist
        windeployqt D1HeroPlanner.exe --no-compiler-runtime --no-opengl-sw --no-system-d3d-compiler --no-virtualkeyboard --no-translations --no-quick-import
      shell: cmd

    - name: Upload
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: D1HeroPlanner-Windows-x86
        path: dist
