name: Windows

on: [ push, pull_request ]
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  PROJECT_NAME: 'D1HeroPlanner'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.2.4'
        cache: 'true'
        modules: 'qtmultimedia'

    - name: Configure
      run: cmake -S. -Bbuild

    - name: Make
      run: cmake --build build -j $(nproc) --config Release

    - name: Package
      run: |
        mkdir dist
        copy build\Release\${{ env.PROJECT_NAME }}.exe dist
        cd dist
        windeployqt ${{ env.PROJECT_NAME }}.exe --no-compiler-runtime --no-opengl-sw --no-system-d3d-compiler --no-virtualkeyboard --no-translations --no-quick-import
      shell: cmd

    - name: Upload
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-Windows-x64
        path: dist

    - name: Upload bin
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}.exe
        path: build\Release\${{ env.PROJECT_NAME }}.exe

    - name: Upload translations
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-Translations
        path: languages
